<a href="https://colab.research.google.com/github/alexandergribenchenko/Test_R5_DE/blob/main/NB_Test_R5_DE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd

In [23]:
path_github = 'https://raw.githubusercontent.com/alexandergribenchenko/Test_R5_DE/main/data/dataset.csv'

In [24]:
df = pd.read_csv(path_github, dtype=object)
df

,num_documento_cliente,tipo_documento_cliente,codigo_tienda,total_compra,tipo_tienda,latitud_tienda,longitud_tienda,id_barrio,nombre_barrio,fecha_compra
0,6861792605025121524,1,14812028,22218042,Tienda especializada,3.40211808,-76.52568134,737998244,Canaverales Los Samanes,2022-06-15 15:49:11
1,1552970090928921643,1,14388938,21583407,Tienda especializada,3.468765417,-76.48493586,737998896,Jorge Eliecer Gaitan,2022-10-02 22:14:54
2,-4075904842556875666,1,12370698,6185349,Tienda especializada,3.40074292,-76.52483946,737998244,Canaverales Los Samanes,2022-01-10 0:27:57
3,3539339627033221084,1,10313583,10313583,Tienda especializada,3.369543673,-76.52366403,738000400,Lili,2022-09-02 16:30:24
4,5595554501572542610,1,14358071,28716142,Tienda especializada,3.419045741,-76.49772993,737996734,El Poblado,2022-03-20 2:56:49
...,...,...,...,...,...,...,...,...,...,...
94605,-6859292209449934659,2,1116,558,Supermercado,3.47740375,-76.52670515,737998252,Chipichape,2022-04-30 14:38:39
94606,-1762474661445594290,2,745,372.5,Tienda Outlet,3.41432528,-76.54798624,737998095,Unidad Residencial Santiago de Cali,2022-01-07 23:41:02
94607,-1762474661445594290,2,745,372.5,Supermercado,3.45120421,-76.5329424,737998832,San Pedro,2022-11-09 13:46:59
94608,-2708241712915270749,2,4090,2045,Supermercado,3.42755068,-76.49999127,737995769,Julio Rincón,2022-06-15 2:55:38
94609,4476350616100556296,2,15409667,15409667,Tienda especializada,3.450511126,-76.53831413,737998685,El Peñón,2022-02-11 5:45:36

# Pregunta 03.

## 03.01. ¿Cuáles son las tiendas con compras de al menos 100 clientes diferentes?

In [26]:
df_Q_03_01 = df.groupby(['codigo_tienda'], as_index=False).\
           agg(n_unique_clientes=('num_documento_cliente', lambda x: len(set(x)))).\
           sort_values(by=['n_unique_clientes'], ascending=[False]).reset_index(drop=True)
df_Q_03_01 = df_Q_03_01[df_Q_03_01.n_unique_clientes>=100]
df_Q_03_01

    codigo_tienda  n_unique_clientes
0             745                660
1        11303609                525
2             829                482
3             747                457
4             812                457
..            ...                ...
248          1187                102
249          5401                102
250          2182                101
251          3588                100
252          4594                100

[253 rows x 2 columns]

## 03.02. ¿Cuáles son los 5 barrios donde la mayor cantidad de clientes únicos realizan compras en tiendas tipo 'Tienda Regional'?

In [30]:
df_Q_03_02 = df[df.tipo_tienda=='Tienda Regional']
df_Q_03_02 = df_Q_03_02.groupby(['id_barrio', 'nombre_barrio'], as_index=False).\
           agg(n_unique_clientes=('num_documento_cliente', lambda x: len(set(x)))).\
           sort_values(by=['n_unique_clientes'], ascending=[False]).reset_index(drop=True)
df_Q_03_02 = df_Q_03_02.head()
df_Q_03_02

   id_barrio                        nombre_barrio  n_unique_clientes
0  738000377                       Unicentro Cali                354
1  737998204                            Versalles                328
2  737999419                              El Sena                287
3  737998095  Unidad Residencial Santiago de Cali                276
4  737998838                               Calima                250

In [7]:
df.tipo_tienda.value_counts(dropna=False)

Supermercado            37690
Tienda especializada    37067
Tienda Outlet            9374
Tienda Regional          7076
Hipermercado             3386
Minimercado                17
Name: tipo_tienda, dtype: int64

In [8]:
df.tipo_documento_cliente.value_counts(dropna=False)

1    91889
2     2691
3       16
4       12
9        2
Name: tipo_documento_cliente, dtype: int64

In [9]:
df.id_barrio.value_counts(dropna=False)

737998832    5304
738000407    4352
737998194    3811
737998252    3437
738000377    3157
             ...
737998112       1
737996724       1
737996915       1
737998951       1
737996970       1
Name: id_barrio, Length: 277, dtype: int64

In [10]:
df.nombre_barrio.value_counts(dropna=False)

San Pedro                           5304
Urbanización San Juaquín            4352
Santa Mónica Residencial            3811
Chipichape                          3437
Unicentro Cali                      3157
                                    ...
Altos de Santa Isabel La Morelia       1
Terrón Colorado                        1
San Benito                             1
Los Conquistadores                     1
Polvorines                             1
Name: nombre_barrio, Length: 277, dtype: int64